require 'sorcerer'
require 'sourcify'
require 'optiflag'

require_relative './DependencyGraph'
require_relative './Context'
require_relative './Tokens'
require_relative './ImmutableStack'
require_relative './ImmutableQueue'
require_relative './interpretation_context'
require_relative './Production'
require_relative './AstRewritter'
require_relative './Transformer'
